import Navbar from "@/components/navbar";
import Sidebar from "@/components/sideBar";
import MiniNav from "@/components/miniNav";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <div className="fixed inset-x-0 top-0 z-30 bg-gray-200">
          <Navbar />
        </div>

        <div className="pt-16 flex min-h-screen">
          <div className="fixed left-0 top-16 bottom-0 w-64 overflow-y-auto bg-gray-200">
            <Sidebar />
          </div>

          <main className="ml-64 flex-1 overflow-auto border border-r border-blue-500">
            <MiniNav />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
